### ISSUE TITLE
Violation of copyright and must be removed

### ISSUE THREAD

**Issue by enaiburg12** [Ditectrev/Professional-Scrum-Product-Owner-PSPO-I-Practice-Tests-Exams-Questions-Answers#2]
This site violates copyright and trademark laws and must be removed immediately or we will be forced to take legal action. Please contact us ASAP at eric.naiburg@scrum.org

Thank you,

Eric Naiburg
COO
Scrum.org

**Comment by danieldanielecki** [comment]
@enaiburg12, the trademarks in https://www.scrum.org/scrumorg-trademarks-and-copyrights indeed mention `PROFESSIONAL SCRUM PRODUCT OWNER` and `PROFESSIONAL SCRUM` in regards to what's being used in this repo. Tens of websites are using that, but we'll naturally remove those 2. The dispute about the `PROFESSIONAL SCRUM PRODUCT OWNER` has been in sync with Udemy Legal since yesterday, and these trademarks will be removed from this repo after syncing with Udemy Legal what's allowed. Additionally, `PROFESSIONAL SCRUM` will be removed as well, even though the dispute isn't about that we'll remove that as well. Do expect changes by the end of next week and the communication channel over Udemy Legal is more clear and structured, let's keep it there.

Thanks for the feedback, and apologizes for overlooking those 2 trademarks; as said - it's widely used on tens of websites, but it was a mistake and is about to be fixed next week.

All the best, Daniel
